ftn95 array /checkmate /link
ftn95 uninit /checkmate /link
ftn95 bounds1 /checkmate /link
ftn95 bounds2 /checkmate /link
ftn95 const /checkmate /link
ftn95 overflow /checkmate /link
ftn95 args /checkmate
ftn95 args1 /checkmate
slink args.lnk
ftn95 func /checkmate
ftn95 func1 /checkmate
slink func.lnk
ftn95 pointer1 /checkmate /link
ftn95 pointer2 /checkmate /link
ftn95 doloop.f90 /checkmate /link
